# Generated by Django 2.2.2 on 2019-08-17 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0013_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.IntegerField()),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.IntegerField()),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='id',
        ),
        migrations.AddField(
            model_name='checkout',
            name='checkid',
            field=models.CharField(default=None, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='checkout',
            name='checkout_user',
            field=models.ForeignKey(default=None, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='previousorder',
            name='order_address',
            field=models.ForeignKey(default=None, on_delete='CASCADE', to='MainApp.Checkout'),
        ),
        migrations.AddField(
            model_name='previousorder',
            name='order_product',
            field=models.ForeignKey(default=None, on_delete='CASCADE', to='MainApp.Product'),
        ),
        migrations.AddField(
            model_name='previousorder',
            name='order_user',
            field=models.ForeignKey(default=None, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='order_address',
            field=models.ForeignKey(default=None, on_delete='CASCADE', to='MainApp.Checkout'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_product',
            field=models.ForeignKey(default=None, on_delete='CASCADE', to='MainApp.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_user',
            field=models.ForeignKey(default=None, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
